- name: "Install package"
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: Install xclip
      dnf:
        name=xclip
        state=latest
      when: ansible_distribution == "Fedora"
